title: Hello, world! I'm Abishek Murali
description: > # this means to ignore newlines until "baseurl:"
  All things that lie at the intersection of randomness and data science.

# Author Settings
author: Abishek Murali # add your name
author-img: abishek-murali.jpg # add your photo
about-author: 'Data scientist \n Graduate from UBC, Vancouver \n Trying to find beauty in randomness \n You can find me on twitter and linkedin as well.'
twitter: abimojo # add your Twitter handle
facebook: cambridge.analytica # add your Facebook handle
github: abimur-123/projects # add your Github handle
linkedin: abishek-murali-a71025a9 # add your Linkedin handle
email: abimur@gmail.com # add your Email address

# Disqus
discus-identifier: abimur # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
