title: Hello, world! I'm Abishek Murali
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Author Settings
author: Abishek # add your name
author-img: abishek-murali.jpg # add your photo
about-author: Masters student at UBC, and an aspiring data scientist. Always willing to learn. # add description
twitter: abimojo # add your Twitter handle
facebook: # add your Facebook handle
github: abimur-123 # add your Github handle
linkedin: # add your Linkedin handle
email: abimur@gmail.com # add your Email address

# Disqus
discus-identifier: abimur # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
